### PR TITLE
Continuation of the previous app icon PR

### PR DESCRIPTION
**Pull request by Fatih20**

### CODE REVIEW

**Comment by Fatih20** [comment]
Have you actually make it so that the icons are actually used by the app? It still uses this when I compiled it.
image

**Comment by Fatih20** [comment]
And this is _**NOT**_, I repeat **_NOT_** done. _**DO NOT**_ merge this, I _**DO NOT**_ want to make another PR.

**Comment by aharotias2** [comment]
@Fatih20 
Thank you very much.
I couldn't install the icon, so I modified meson.build and committed.
https://github.com/aharotias2/tatap/commit/476a42c96451174a0188d15f95f9db5318ca4fab

**Comment by Fatih20** [comment]
> @Fatih20
> Thank you very much.
> I couldn't install the icon, so I modified meson.build and committed.
> [476a42c](https://github.com/aharotias2/tatap/commit/476a42c96451174a0188d15f95f9db5318ca4fab)

So does the app uses my icon now when installed?

**Comment by aharotias2** [comment]
No, It will fail to install because 48 and 64 icons are not merged to master branch yet.
You may can merge or rebase master branch into your branch and install then it will use the icons.
Please try it.

**Comment by Fatih20** [comment]
> No, It will fail to install because 48 and 64 icons are not merged to master branch yet.
> You may can merge or rebase master branch into your branch and install then it will use the icons.
> Please try it.

I've merged this branch with master. Can you try building from this branch and give me feedback if the icons work?

**Comment by aharotias2** [comment]
I'm sorry, I failed again.
Can you merge the master branch one more time?

**Comment by Fatih20** [comment]
Is this application meant to be published on the elementary appcenter?

**Comment by aharotias2** [comment]
Yes.

**Comment by Fatih20** [comment]
> No, It will fail to install because 48 and 64 icons are not merged to master branch yet.
> You may can merge or rebase master branch into your branch and install then it will use the icons.
> Please try it.

From this message, I think you don't know that elementary's applications uses several sizes, not just 128, 64, 48. This is likely why the icons still have not showed up. You should give this a read this if you're developing app for the eOS.
https://docs.elementary.io/hig/
The sizes used are mentioned in the iconography section.

**Comment by Fatih20** [comment]
It's also probably why you mistakenly merged my previous PR. Because you thought applications only uses one sizes for their icon, and so my work is done.

**Comment by aharotias2** [comment]
Thank you very much.
I will use the icon you made.

**Comment by ryonakano** [comment]
@aharotias2 You can edit any file in the `new-icons` branch of @Fatih20's fork on GitHub, so you may want to edit `data/meson.build` in that branch directly instead of adding changes in your master branch and ask him to merge that change into this branch.

**Comment by ryonakano** [comment]
Screenshot from 2021-05-08 21-34-04

OK, I confirmed this branch works with the following changes:

```diff
diff --git a/data/meson.build b/data/meson.build
index 438ad8a..ad4721e 100644
--- a/data/meson.build
+++ b/data/meson.build
@@ -2,7 +2,8 @@ icon_sizes = ['48', '64', '128']
 
 foreach i : icon_sizes
     install_data(
-        join_paths('icons', i, meson.project_name() + '.svg'),
+        join_paths('icons', i, 'icons.svg'),
+        rename: meson.project_name() + '.svg',
         install_dir: join_paths(get_option('datadir'), 'icons', 'hicolor', i + 'x' + i, 'apps')
     )
 endforeach
```

(or rename the icon name in this branch to `com.github.aharotias2.tatap.svg`; in this case you don't need the above changes)

**Comment by aharotias2** [comment]
@ryonakano 
Thank you!
I have confirmed that the application icon appears in the menu and dock.

**Comment by Fatih20** [comment]
Oh it works now I guess. I'll rebase my fork then.

**Comment by Fatih20** [comment]
image
It looked like this on the dock though.

**Comment by Fatih20** [comment]
It works like this in the dock.
image

**Comment by aharotias2** [comment]
I'm aware of the problem, but I don't know how to fix it. I'll fix it as soon as I find out.

**Comment by ryonakano** [comment]
Removing the following line fixes the issue on my local:

```diff
diff --git a/data/tatap.desktop.in b/data/tatap.desktop.in
index 14617e0..a155fc7 100644
--- a/data/tatap.desktop.in
+++ b/data/tatap.desktop.in
@@ -8,5 +8,4 @@ Icon=com.github.aharotias2.tatap
 Type=Application
 Terminal=false
 Categories=Graphics
-StartupWMClass=Tatap
 Keywords=Picture;Image;Viewer;
```

**Comment by aharotias2** [comment]
@ryonakano 
Thank you!
The problem of two icons appearing in the dock has been fixed.

**Comment by aharotias2** [comment]
@Fatih20 
Thank you!
I have updated meson.build etc so the icons you maid now are appeared.
Please merge master branch.

**Comment by Fatih20** [comment]
Any complaints you have with this icon? Go ahead and nitpick on it.

**Comment by aharotias2** [comment]
It looks very good. I am satisfied.

**Comment by Fatih20** [comment]
Ok then. Go ahead and merge it.

**Comment by aharotias2** [comment]
Thank you very much!

**Comment by ryonakano** [comment]
@Fatih20 Thank you very much for your hard work and patience, really looks sweet! :tada:

**Comment by Fatih20** [comment]
You're welcome!

**Comment by aharotias2** [comment]
I merged the Fatih20 pull request.
But it doesn't close automatically so I close it manually.
Thank you to those involved.

**Pull request closed without merging**
