### PR TITLE
add initial Debian source packaging files

### PR DESCRIPTION
**Pull request by SwampRabbit**
add initial Debian source packaging files to build .deb packages for Debian/Ubuntu based distribution repositories

### CODE REVIEW

**Comment by aharotias2** [comment]
I have merged your commits.
I will try to build a debian package using this files.
Thank you!

**Comment by SwampRabbit** [comment]
@aharotias2 you can continue to use your GitHub builds to create a release .deb file.  

These files are more specifically for Debian based distro package maintainers who create the .deb for actual repositories.
Sometimes the GitHub automated builds have issues with building packages using these files.

But I know they are good because I'm maintaining ParaPara amd64, i386, and armhf builds now for MX Linux.

In the debian/control file you'll notice that I've included webp-pixbuf-loader as a recommend, this allows ParaPara to work with webp images very nicely.

**Comment by aharotias2** [comment]
Wow I tried to install ParaPara from MX Linux repository, and open webp file, and as a result, that is succeed.
Thank you very much!

**Comment by SwampRabbit** [comment]
@aharotias2 you're very welcome, thank you for making such a cool image viewer!

I started a forum thread to get feedback from our users.
https://forum.mxlinux.org/viewtopic.php?p=670365#p670365

**Pull request merged**
