### PR TITLE
New App Icons

### PR DESCRIPTION
**Pull request by Fatih20**
This is the first icon that I've made. What do you think @aharotias2 @ryonakano?

### CODE REVIEW

**Comment by aharotias2** [comment]
@Fatih20 
It's good.
I think it would be better if some photos overlap.
Thank you.

**Comment by Fatih20** [comment]
> @Fatih20
> It's good.
> I think it would be better if some photos overlap.
> Thank you.

Several polaroid overlapping with each other?

**Comment by aharotias2** [comment]
＠Fatih20
Yes!!

**Comment by Fatih20** [comment]
> ＠Fatih20
> Yes!!

Although it would be cool, I doubt it would be legible on smaller sizes such as 48 which is commonly used for the dock. So I think I'd go ahead with the singular polaroid.

**Comment by aharotias2** [comment]
@Fatih20
It's right. I agree.

**Comment by aharotias2** [comment]
However I want something one point . Can't you?

**Comment by Fatih20** [comment]
> However I want something one point . Can't you?

What do you mean?

**Comment by aharotias2** [comment]
Anything is fine, so please draw something in the picture.

**Comment by Fatih20** [comment]
> Anything is fine, so please draw something in the picture.

Other than adding light reflection to the dark part to make it even more like polaroid, I don't think I'll add anything such as an actual picture. Because it would draw focus away on the fact that it's polaroid and the picture wouldn't be shown in the best way possible. If you wanted pictures, it's better to go with the design of the elementary Photo Viewer.

**Comment by aharotias2** [comment]
I understand. I want to use your first icon (without reflection). Can I use it?

**Comment by Fatih20** [comment]
> I understand. I want to use your first icon (without reflection). Can I use it?

Yeah sure.

**Comment by Fatih20** [comment]
Can you make changes to `master` so that the app recognizes these icon and uses them when compiled? I'll rebase this branch afterwards. I need to see how good the icon looks in practice.

**Comment by aharotias2** [comment]
@Fatih20 
Thank you very much.
I'll try it tonight.

**Comment by Fatih20** [comment]
I'm sorry, what? This pull request is clearly not done. Why did you merge this?

**Comment by aharotias2** [comment]
@Fatih20 
Excuse me. I didn't know what to do and made an operational mistake.

**Comment by Fatih20** [comment]
What the hell dude, you didn't even ask me if it's done.

**Comment by aharotias2** [comment]
I'm sorry, I didn't read your message properly.
I didn't know it shouldn't be merged.

**Comment by Fatih20** [comment]
Fine whatever, I'll just make another pull request to continue this one.

**Comment by aharotias2** [comment]
Thank you.

**Pull request merged**
